steps:
  # Step 1: Build the Nginx Engine
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend' # <--- Walk into the frontend folder first!
    args: 
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-spinthewheel-repo/spinthewheel-frontend'
      - '.'

  # Step 2: Push to the Warehouse
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: 
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-spinthewheel-repo/spinthewheel-frontend'

  # Step 3: Deploy to Cloud Run (With Admin privileges!)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'frontend'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'spinthewheel-frontend-service'
      - '--image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-spinthewheel-repo/spinthewheel-frontend'
      - '--region=asia-southeast1'
      - '--port=80'
      - '--allow-unauthenticated'