steps:
  # Step 1: Build the Docker Image (The Engine)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-spinthewheel-repo/spinthewheel-backend'
      - '.'

  # Step 2: Push the Image to the Warehouse (Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-spinthewheel-repo/spinthewheel-backend'

  # Step 3: Deploy to Cloud Run (With Admin Privileges)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'spinthewheel-backend-service'
      - '--image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-spinthewheel-repo/spinthewheel-backend'
      - '--region=asia-southeast1'
      - '--allow-unauthenticated' # <--- The Robot creates the room and unlocks the door to the public!