steps:
  # Step 1: Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend' # <--- Walk into the backend folder first!
    args: 
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-spinthewheel-repo/spinthewheel-backend'
      - '.'

  # Step 2: Push to the Warehouse
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend' # <--- Run this from the backend folder
    args: 
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-spinthewheel-repo/spinthewheel-backend'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'backend' # <--- Run this from the backend folder
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'spinthewheel-backend-service'
      - '--image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/my-spinthewheel-repo/spinthewheel-backend'
      - '--region=asia-southeast1'
      - '--allow-unauthenticated'